/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class CssExtDslIdeaModule extends AbstractCssExtDslIdeaModule {
}
