/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang;

import org.eclipse.fx.ide.css.idea.lang.AbstractCssDslFileType;

@SuppressWarnings("all")
public class CssDslFileType extends AbstractCssDslFileType {
  public final static CssDslFileType INSTANCE = new CssDslFileType();
  
  public CssDslFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(CssDslLanguage) is undefined");
  }
}
