/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslFileType;
import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class CssExtDslFileImpl extends BaseXtextFile {

	public CssExtDslFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, CssExtDslLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return CssExtDslFileType.INSTANCE;
	}
}
