/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.ui.labeling;

import org.eclipse.fx.ide.css.cssDsl.CssProperty;
import org.eclipse.fx.ide.css.cssDsl.Ruleset;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CssDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  public CharSequence image(final Ruleset ele) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("icons/selector_16x16.png");
    return _builder;
  }
  
  public CharSequence image(final CssProperty ele) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("icons/property_16x16.png");
    return _builder;
  }
}
