/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.highlighting;

import org.eclipse.fx.ide.css.idea.highlighting.CssDslBaseColorSettingsPage;

@SuppressWarnings("all")
public class CssDslColorSettingsPage extends CssDslBaseColorSettingsPage {
}
