/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.scoping;

import org.eclipse.fx.ide.css.cssext.scoping.AbstractCssExtDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CssExtDslScopeProvider extends AbstractCssExtDslScopeProvider {
}
