/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class CssDslFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(CssDslFileType.INSTANCE, AbstractCssDslFileType.DEFAULT_EXTENSION);
	}

}
