/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class CssDslLanguage extends AbstractXtextLanguage {

	public static final CssDslLanguage INSTANCE = new CssDslLanguage();

	private CssDslLanguage() {
		super("org.eclipse.fx.ide.css.CssDsl");
	}

}
