/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.highlighting;

import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class CssExtDslBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public CssExtDslBaseColorSettingsPage() {
		CssExtDslLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return CssExtDslLanguage.INSTANCE.getDisplayName();
	}
}
