/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.completion;

import org.eclipse.fx.ide.css.idea.completion.AbstractCssDslCompletionContributor;
import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;

@SuppressWarnings("all")
public class CssDslCompletionContributor extends AbstractCssDslCompletionContributor {
  public CssDslCompletionContributor() {
    this(CssDslLanguage.INSTANCE);
  }
  
  public CssDslCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
