/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea;

@SuppressWarnings("all")
public class CssExtDslIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
