/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;

public class CssDslExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return CssDslLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
