/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.fx.ide.css.cssext.ui.internal.CssextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class CssExtDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CssextActivator.getInstance().getInjector("org.eclipse.fx.ide.css.cssext.CssExtDsl");
	}

}
