/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang


class CssExtDslFileType extends AbstractCssExtDslFileType {
	public static final CssExtDslFileType INSTANCE = new CssExtDslFileType()
	
	new() {
		super(CssExtDslLanguage.INSTANCE)
	}
}
