/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.highlighting;

import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class CssDslSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public CssDslSemanticHighlightVisitor() {
		CssDslLanguage.INSTANCE.injectMembers(this);
	}
}
