/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class CssExtDslCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public CssExtDslCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(CssExtDslLanguage.INSTANCE, psiModificationTracker);
	}

}
