/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.completion

import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class CssDslCompletionContributor extends AbstractCssDslCompletionContributor {
	new() {
		this(CssDslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
