/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CssExtDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
