/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang


class CssDslFileType extends AbstractCssDslFileType {
	public static final CssDslFileType INSTANCE = new CssDslFileType()
	
	new() {
		super(CssDslLanguage.INSTANCE)
	}
}
