/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class CssDslIdeaModule extends AbstractCssDslIdeaModule {
}
