/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class CssDslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new CssDslStandaloneSetupIdea().createInjector
	}

}
