/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class CssDslCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public CssDslCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(CssDslLanguage.INSTANCE, psiModificationTracker);
	}

}
