/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang;

import org.eclipse.fx.ide.css.cssext.idea.lang.AbstractCssExtDslFileType;

@SuppressWarnings("all")
public class CssExtDslFileType extends AbstractCssExtDslFileType {
  public final static CssExtDslFileType INSTANCE = new CssExtDslFileType();
  
  public CssExtDslFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(CssExtDslLanguage) is undefined");
  }
}
