/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang.pom;

import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class CssDslPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public CssDslPomDeclarationSearcher() {
		super(CssDslLanguage.INSTANCE);
	}
}
