/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.fx.ide.css.cssDsl.CssDslPackage
 * @generated
 */
public interface CssDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CssDslFactory eINSTANCE = org.eclipse.fx.ide.css.cssDsl.impl.CssDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Stylesheet</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stylesheet</em>'.
   * @generated
   */
  Stylesheet createStylesheet();

  /**
   * Returns a new object of class '<em>Charset Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Charset Rule</em>'.
   * @generated
   */
  CharsetRule createCharsetRule();

  /**
   * Returns a new object of class '<em>Import Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Rule</em>'.
   * @generated
   */
  ImportRule createImportRule();

  /**
   * Returns a new object of class '<em>Page Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Rule</em>'.
   * @generated
   */
  PageRule createPageRule();

  /**
   * Returns a new object of class '<em>Media Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media Rule</em>'.
   * @generated
   */
  MediaRule createMediaRule();

  /**
   * Returns a new object of class '<em>Media List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media List</em>'.
   * @generated
   */
  MediaList createMediaList();

  /**
   * Returns a new object of class '<em>Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media</em>'.
   * @generated
   */
  Media createMedia();

  /**
   * Returns a new object of class '<em>Font Face Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Font Face Rule</em>'.
   * @generated
   */
  FontFaceRule createFontFaceRule();

  /**
   * Returns a new object of class '<em>Keyframes Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Keyframes Rule</em>'.
   * @generated
   */
  KeyframesRule createKeyframesRule();

  /**
   * Returns a new object of class '<em>Keyframe Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Keyframe Selector</em>'.
   * @generated
   */
  KeyframeSelector createKeyframeSelector();

  /**
   * Returns a new object of class '<em>Ruleset</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ruleset</em>'.
   * @generated
   */
  Ruleset createRuleset();

  /**
   * Returns a new object of class '<em>Css Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Declaration</em>'.
   * @generated
   */
  CssDeclaration createCssDeclaration();

  /**
   * Returns a new object of class '<em>Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Selector</em>'.
   * @generated
   */
  Selector createSelector();

  /**
   * Returns a new object of class '<em>Simple Selector For Negation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Selector For Negation</em>'.
   * @generated
   */
  SimpleSelectorForNegation createSimpleSelectorForNegation();

  /**
   * Returns a new object of class '<em>Css Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Selector</em>'.
   * @generated
   */
  CssSelector createCssSelector();

  /**
   * Returns a new object of class '<em>Simple Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Selector</em>'.
   * @generated
   */
  SimpleSelector createSimpleSelector();

  /**
   * Returns a new object of class '<em>Class Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Selector</em>'.
   * @generated
   */
  ClassSelector createClassSelector();

  /**
   * Returns a new object of class '<em>Element Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Selector</em>'.
   * @generated
   */
  ElementSelector createElementSelector();

  /**
   * Returns a new object of class '<em>Universal Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Universal Selector</em>'.
   * @generated
   */
  UniversalSelector createUniversalSelector();

  /**
   * Returns a new object of class '<em>Id Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Id Selector</em>'.
   * @generated
   */
  IdSelector createIdSelector();

  /**
   * Returns a new object of class '<em>Css Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Property</em>'.
   * @generated
   */
  CssProperty createCssProperty();

  /**
   * Returns a new object of class '<em>Pseudo Class Or Func</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pseudo Class Or Func</em>'.
   * @generated
   */
  PseudoClassOrFunc createPseudoClassOrFunc();

  /**
   * Returns a new object of class '<em>Pseudo Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pseudo Class</em>'.
   * @generated
   */
  PseudoClass createPseudoClass();

  /**
   * Returns a new object of class '<em>Pseudo Class Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pseudo Class Function</em>'.
   * @generated
   */
  PseudoClassFunction createPseudoClassFunction();

  /**
   * Returns a new object of class '<em>Css Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Tok</em>'.
   * @generated
   */
  CssTok createCssTok();

  /**
   * Returns a new object of class '<em>URL Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>URL Type</em>'.
   * @generated
   */
  URLType createURLType();

  /**
   * Returns a new object of class '<em>Attribute Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Selector</em>'.
   * @generated
   */
  AttributeSelector createAttributeSelector();

  /**
   * Returns a new object of class '<em>Symbol Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Symbol Tok</em>'.
   * @generated
   */
  SymbolTok createSymbolTok();

  /**
   * Returns a new object of class '<em>WS Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>WS Tok</em>'.
   * @generated
   */
  WSTok createWSTok();

  /**
   * Returns a new object of class '<em>String Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Tok</em>'.
   * @generated
   */
  StringTok createStringTok();

  /**
   * Returns a new object of class '<em>Number Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number Tok</em>'.
   * @generated
   */
  NumberTok createNumberTok();

  /**
   * Returns a new object of class '<em>Url Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Url Tok</em>'.
   * @generated
   */
  UrlTok createUrlTok();

  /**
   * Returns a new object of class '<em>Color Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color Tok</em>'.
   * @generated
   */
  ColorTok createColorTok();

  /**
   * Returns a new object of class '<em>Identifier Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Identifier Tok</em>'.
   * @generated
   */
  IdentifierTok createIdentifierTok();

  /**
   * Returns a new object of class '<em>Func Tok</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Tok</em>'.
   * @generated
   */
  FuncTok createFuncTok();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CssDslPackage getCssDslPackage();

} //CssDslFactory
