/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fx.ide.css.cssDsl.PageRule#getPseudoPage <em>Pseudo Page</em>}</li>
 *   <li>{@link org.eclipse.fx.ide.css.cssDsl.PageRule#getDeclarations <em>Declarations</em>}</li>
 * </ul>
 *
 * @see org.eclipse.fx.ide.css.cssDsl.CssDslPackage#getPageRule()
 * @model
 * @generated
 */
public interface PageRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Pseudo Page</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pseudo Page</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pseudo Page</em>' attribute.
   * @see #setPseudoPage(String)
   * @see org.eclipse.fx.ide.css.cssDsl.CssDslPackage#getPageRule_PseudoPage()
   * @model
   * @generated
   */
  String getPseudoPage();

  /**
   * Sets the value of the '{@link org.eclipse.fx.ide.css.cssDsl.PageRule#getPseudoPage <em>Pseudo Page</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pseudo Page</em>' attribute.
   * @see #getPseudoPage()
   * @generated
   */
  void setPseudoPage(String value);

  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.fx.ide.css.cssDsl.CssDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see org.eclipse.fx.ide.css.cssDsl.CssDslPackage#getPageRule_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<CssDeclaration> getDeclarations();

} // PageRule
