/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WS Tok</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.fx.ide.css.cssDsl.CssDslPackage#getWSTok()
 * @model
 * @generated
 */
public interface WSTok extends CssTok
{
} // WSTok
