/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.ui;

import com.google.inject.Injector;
import org.eclipse.fx.ide.css.cssext.ui.internal.CssextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CssExtDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CssextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CssextActivator.getInstance().getInjector(CssextActivator.ORG_ECLIPSE_FX_IDE_CSS_CSSEXT_CSSEXTDSL);
	}
	
}
