/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.highlighting;

import org.eclipse.fx.ide.css.cssext.idea.highlighting.CssExtDslBaseColorSettingsPage;

@SuppressWarnings("all")
public class CssExtDslColorSettingsPage extends CssExtDslBaseColorSettingsPage {
}
