/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class CssExtDslFacetType extends AbstractFacetType<CssExtDslFacetConfiguration> {

	public static final FacetTypeId<Facet<CssExtDslFacetConfiguration>> TYPEID = new FacetTypeId<Facet<CssExtDslFacetConfiguration>>("org.eclipse.fx.ide.css.cssext.CssExtDsl");

	public CssExtDslFacetType() {
		super(TYPEID, "org.eclipse.fx.ide.css.cssext.CssExtDsl", "CssExtDsl");
		CssExtDslLanguage.INSTANCE.injectMembers(this);
	}
}
