/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang.pom;

import org.eclipse.fx.ide.css.cssext.idea.lang.CssExtDslLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class CssExtDslPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public CssExtDslPomDeclarationSearcher() {
		super(CssExtDslLanguage.INSTANCE);
	}
}
