/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.fx.ide.css.idea.lang.CssDslFileType;
import org.eclipse.fx.ide.css.idea.lang.CssDslLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class CssDslFileImpl extends BaseXtextFile {

	public CssDslFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, CssDslLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return CssDslFileType.INSTANCE;
	}
}
