/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.ui;

import org.eclipse.fx.ide.css.ui.internal.CssActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CssDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CssActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CssActivator.getInstance().getInjector(CssActivator.ORG_ECLIPSE_FX_IDE_CSS_CSSDSL);
	}
	
}
