/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import org.eclipse.fx.ide.css.cssext.AbstractCssExtDslRuntimeModule;
import org.eclipse.fx.ide.css.cssext.api.ProposalContributionRegistry;
import org.eclipse.fx.ide.css.cssext.extapi.CssExtApi;
import org.eclipse.fx.ide.css.cssext.internal.CssExtImpl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CssExtDslRuntimeModule extends AbstractCssExtDslRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    AnnotatedBindingBuilder<CssExtApi> _bind = binder.<CssExtApi>bind(CssExtApi.class);
    _bind.to(CssExtImpl.class);
    AnnotatedBindingBuilder<ProposalContributionRegistry> _bind_1 = binder.<ProposalContributionRegistry>bind(ProposalContributionRegistry.class);
    _bind_1.toProvider(ProposalContributionRegistry.OSGiServiceProvider.class);
    super.configure(binder);
  }
}
