/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.tests

import com.google.inject.Inject
import org.eclipse.fx.ide.css.cssext.cssExtDsl.CssExtension
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CssExtDslInjectorProvider)
class CssExtDslParsingTest{

	@Inject
	ParseHelper<CssExtension> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
