/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.eclipse.fx.ide.css.cssDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CssDslFactoryImpl extends EFactoryImpl implements CssDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CssDslFactory init()
  {
    try
    {
      CssDslFactory theCssDslFactory = (CssDslFactory)EPackage.Registry.INSTANCE.getEFactory(CssDslPackage.eNS_URI);
      if (theCssDslFactory != null)
      {
        return theCssDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CssDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CssDslPackage.STYLESHEET: return createStylesheet();
      case CssDslPackage.CHARSET_RULE: return createCharsetRule();
      case CssDslPackage.IMPORT_RULE: return createImportRule();
      case CssDslPackage.PAGE_RULE: return createPageRule();
      case CssDslPackage.MEDIA_RULE: return createMediaRule();
      case CssDslPackage.MEDIA_LIST: return createMediaList();
      case CssDslPackage.MEDIA: return createMedia();
      case CssDslPackage.FONT_FACE_RULE: return createFontFaceRule();
      case CssDslPackage.KEYFRAMES_RULE: return createKeyframesRule();
      case CssDslPackage.KEYFRAME_SELECTOR: return createKeyframeSelector();
      case CssDslPackage.RULESET: return createRuleset();
      case CssDslPackage.CSS_DECLARATION: return createCssDeclaration();
      case CssDslPackage.SELECTOR: return createSelector();
      case CssDslPackage.SIMPLE_SELECTOR_FOR_NEGATION: return createSimpleSelectorForNegation();
      case CssDslPackage.CSS_SELECTOR: return createCssSelector();
      case CssDslPackage.SIMPLE_SELECTOR: return createSimpleSelector();
      case CssDslPackage.CLASS_SELECTOR: return createClassSelector();
      case CssDslPackage.ELEMENT_SELECTOR: return createElementSelector();
      case CssDslPackage.UNIVERSAL_SELECTOR: return createUniversalSelector();
      case CssDslPackage.ID_SELECTOR: return createIdSelector();
      case CssDslPackage.CSS_PROPERTY: return createCssProperty();
      case CssDslPackage.PSEUDO_CLASS_OR_FUNC: return createPseudoClassOrFunc();
      case CssDslPackage.PSEUDO_CLASS: return createPseudoClass();
      case CssDslPackage.PSEUDO_CLASS_FUNCTION: return createPseudoClassFunction();
      case CssDslPackage.CSS_TOK: return createCssTok();
      case CssDslPackage.URL_TYPE: return createURLType();
      case CssDslPackage.ATTRIBUTE_SELECTOR: return createAttributeSelector();
      case CssDslPackage.SYMBOL_TOK: return createSymbolTok();
      case CssDslPackage.WS_TOK: return createWSTok();
      case CssDslPackage.STRING_TOK: return createStringTok();
      case CssDslPackage.NUMBER_TOK: return createNumberTok();
      case CssDslPackage.URL_TOK: return createUrlTok();
      case CssDslPackage.COLOR_TOK: return createColorTok();
      case CssDslPackage.IDENTIFIER_TOK: return createIdentifierTok();
      case CssDslPackage.FUNC_TOK: return createFuncTok();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Stylesheet createStylesheet()
  {
    StylesheetImpl stylesheet = new StylesheetImpl();
    return stylesheet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CharsetRule createCharsetRule()
  {
    CharsetRuleImpl charsetRule = new CharsetRuleImpl();
    return charsetRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImportRule createImportRule()
  {
    ImportRuleImpl importRule = new ImportRuleImpl();
    return importRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageRule createPageRule()
  {
    PageRuleImpl pageRule = new PageRuleImpl();
    return pageRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediaRule createMediaRule()
  {
    MediaRuleImpl mediaRule = new MediaRuleImpl();
    return mediaRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediaList createMediaList()
  {
    MediaListImpl mediaList = new MediaListImpl();
    return mediaList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Media createMedia()
  {
    MediaImpl media = new MediaImpl();
    return media;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontFaceRule createFontFaceRule()
  {
    FontFaceRuleImpl fontFaceRule = new FontFaceRuleImpl();
    return fontFaceRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public KeyframesRule createKeyframesRule()
  {
    KeyframesRuleImpl keyframesRule = new KeyframesRuleImpl();
    return keyframesRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public KeyframeSelector createKeyframeSelector()
  {
    KeyframeSelectorImpl keyframeSelector = new KeyframeSelectorImpl();
    return keyframeSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ruleset createRuleset()
  {
    RulesetImpl ruleset = new RulesetImpl();
    return ruleset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssDeclaration createCssDeclaration()
  {
    CssDeclarationImpl cssDeclaration = new CssDeclarationImpl();
    return cssDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Selector createSelector()
  {
    SelectorImpl selector = new SelectorImpl();
    return selector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleSelectorForNegation createSimpleSelectorForNegation()
  {
    SimpleSelectorForNegationImpl simpleSelectorForNegation = new SimpleSelectorForNegationImpl();
    return simpleSelectorForNegation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssSelector createCssSelector()
  {
    CssSelectorImpl cssSelector = new CssSelectorImpl();
    return cssSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleSelector createSimpleSelector()
  {
    SimpleSelectorImpl simpleSelector = new SimpleSelectorImpl();
    return simpleSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassSelector createClassSelector()
  {
    ClassSelectorImpl classSelector = new ClassSelectorImpl();
    return classSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ElementSelector createElementSelector()
  {
    ElementSelectorImpl elementSelector = new ElementSelectorImpl();
    return elementSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UniversalSelector createUniversalSelector()
  {
    UniversalSelectorImpl universalSelector = new UniversalSelectorImpl();
    return universalSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdSelector createIdSelector()
  {
    IdSelectorImpl idSelector = new IdSelectorImpl();
    return idSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssProperty createCssProperty()
  {
    CssPropertyImpl cssProperty = new CssPropertyImpl();
    return cssProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PseudoClassOrFunc createPseudoClassOrFunc()
  {
    PseudoClassOrFuncImpl pseudoClassOrFunc = new PseudoClassOrFuncImpl();
    return pseudoClassOrFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PseudoClass createPseudoClass()
  {
    PseudoClassImpl pseudoClass = new PseudoClassImpl();
    return pseudoClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PseudoClassFunction createPseudoClassFunction()
  {
    PseudoClassFunctionImpl pseudoClassFunction = new PseudoClassFunctionImpl();
    return pseudoClassFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssTok createCssTok()
  {
    CssTokImpl cssTok = new CssTokImpl();
    return cssTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public URLType createURLType()
  {
    URLTypeImpl urlType = new URLTypeImpl();
    return urlType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeSelector createAttributeSelector()
  {
    AttributeSelectorImpl attributeSelector = new AttributeSelectorImpl();
    return attributeSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SymbolTok createSymbolTok()
  {
    SymbolTokImpl symbolTok = new SymbolTokImpl();
    return symbolTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WSTok createWSTok()
  {
    WSTokImpl wsTok = new WSTokImpl();
    return wsTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringTok createStringTok()
  {
    StringTokImpl stringTok = new StringTokImpl();
    return stringTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NumberTok createNumberTok()
  {
    NumberTokImpl numberTok = new NumberTokImpl();
    return numberTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UrlTok createUrlTok()
  {
    UrlTokImpl urlTok = new UrlTokImpl();
    return urlTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ColorTok createColorTok()
  {
    ColorTokImpl colorTok = new ColorTokImpl();
    return colorTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdentifierTok createIdentifierTok()
  {
    IdentifierTokImpl identifierTok = new IdentifierTokImpl();
    return identifierTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FuncTok createFuncTok()
  {
    FuncTokImpl funcTok = new FuncTokImpl();
    return funcTok;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssDslPackage getCssDslPackage()
  {
    return (CssDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CssDslPackage getPackage()
  {
    return CssDslPackage.eINSTANCE;
  }

} //CssDslFactoryImpl
