/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.fx.ide.css.cssDsl.CssDslPackage;
import org.eclipse.fx.ide.css.cssDsl.IdSelector;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Id Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IdSelectorImpl extends CssSelectorImpl implements IdSelector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IdSelectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CssDslPackage.Literals.ID_SELECTOR;
  }

} //IdSelectorImpl
