/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.ui.contentassist;

import org.eclipse.fx.ide.css.cssext.ui.contentassist.AbstractCssExtDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CssExtDslProposalProvider extends AbstractCssExtDslProposalProvider {
}
