/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCssDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.fx.ide.css.cssDsl.CssDslPackage.eINSTANCE);
		return result;
	}
	
}
