/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.cssext.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class CssExtDslLanguage extends AbstractXtextLanguage {

	public static final CssExtDslLanguage INSTANCE = new CssExtDslLanguage();

	private CssExtDslLanguage() {
		super("org.eclipse.fx.ide.css.cssext.CssExtDsl");
	}

}
