/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class CssDslScopeProvider extends AbstractCssDslScopeProvider {

}
