/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea;

import org.eclipse.fx.ide.css.idea.AbstractCssDslIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class CssDslIdeaModule extends AbstractCssDslIdeaModule {
}
