/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.completion;

import org.eclipse.xtext.idea.completion.AbstractCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractCssDslCompletionContributor extends AbstractCompletionContributor {
	public AbstractCssDslCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
