/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class CssDslFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
