/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCssDslScopeProvider extends DelegatingScopeProvider {
}
