/**
 * generated by Xtext 2.9.0
 */
package org.eclipse.fx.ide.css;

import org.eclipse.fx.ide.css.CssDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CssDslStandaloneSetup extends CssDslStandaloneSetupGenerated {
  public static void doSetup() {
    CssDslStandaloneSetup _cssDslStandaloneSetup = new CssDslStandaloneSetup();
    _cssDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
